import "@/styles/globals.css";
import { type FC } from "react";
import { ThemeProvider } from "@/components/theme-provider";
type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="">
        <ThemeProvider>{props.children} </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
